// <auto-generated />
using System;
using Dataaccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dataaccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302093742_commandNullableParams")]
    partial class commandNullableParams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dataaccess.Repository.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("Dataaccess.Repository.Entities.CommandLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("angle")
                        .HasColumnType("double precision");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CommandLog");
                });

            modelBuilder.Entity("Dataaccess.Repository.Entities.Telemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ambientTemperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision");

                    b.Property<double>("bladePitch")
                        .HasColumnType("double precision");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("gearboxTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("generatorTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("nacelleDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("powerOutput")
                        .HasColumnType("double precision");

                    b.Property<double>("rotorSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("turbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("turbineName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<double>("vibration")
                        .HasColumnType("double precision");

                    b.Property<double>("windDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("windSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("Dataaccess.Repository.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
